# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - name: Setup environment variables
      run: |
        echo "NODE_ENV=$NODE_ENV"   
        echo "$DATABASE_URL"   
        echo "DATABASE_URL=$DATABASE_URL"   
        echo "DATABASE_URL=$DIRECT_URL"   
        echo "NEXTAUTH_URL=$NEXTAUTH_URL"   
        echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET"   
        echo "BACKEND_URL=$BACKEND_URL"   
        echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"   
        echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET"   
        echo "NEXT_PUBLIC_FILESTACK_API_KEY=$NEXT_PUBLIC_FILESTACK_API_KEY"   
        echo "SENTRY_ORG=$SENTRY_ORG"   
        echo "SENTRY_PROJECT=$SENTRY_PROJECT"   
        echo "SENTRY_DSN=$SENTRY_DSN"   
        echo "SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN"   
        echo "RESEND_API_KEY=$RESEND_API_KEY"   
        echo "RECIPIENT_EMAIL=$RECIPIENT_EMAIL"   
        echo "RESEND_TRANSCRIPTION_STATUS_EMAIL=$RESEND_TRANSCRIPTION_STATUS_EMAIL"   
        echo "REDIS_HOST=$REDIS_HOST"   
        echo "REDIS_USERNAME=$REDIS_USERNAME"   
        echo "REDIS_PASSWORD=$REDIS_PASSWORD"   
        echo "REDIS_PORT=$REDIS_PORT"   
        echo "REDIS_TIMEOUT=$REDIS_TIMEOUT"
    - run: npm run build
    - run: pm2 restart takenote
    # - run: sudo systemctl restart nginx
